language: node_js

addons:
  hosts:
    - web_tests.nr.jcx.ovh # For saucelabs connect

node_js:
  # Supported Versions
  - "8.10" # Min version
  - "10"
  - "12"
  # Latest stable
  - "node"

# Run tests

install:
  - npm install
script:
  # Run live tests
  - npm run test:run
  # Report live-only coverage to github.
  - npx nyc report --reporter=text | node .github/ci/mock-reporter.js
  # Run mocked tests
  - npm run test:run:mock
  # Report live-only coverage to github.
  - npx nyc report --reporter=text | node .github/ci/live-reporter.js
  # Report all tests to codecov
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
jobs:
  include:
    - stage: Sauce Labs
      node_js: 10
      script:
        - chmod +x .github/ci/install-sauceconnect.sh
        - npm run test:web:saucelabs
      after_success:
        - node ./.github/ci/saucelabs_bot_travis.js
      env:
        - STAGE=SAUCELABS

# Deploy on tags
deploy:
  provider: npm
  email: $NPME
  api_key: $NPMP
  edge: true # opt in to dpl v2
  on:
    # Only deploy on a tagged commit
    tags: true
    # Don't deploy on the saucelabs stage.
    condition: "$STAGE != SAUCELABS"
    node_js: 10
