language: node_js

addons:
  hosts:
    - web_tests.nr.jcx.ovh # For saucelabs connect

node_js:
  # Supported Versions
  - "8.10" # Min version
  - "10"
  - "12"
  # Latest stable
  - "node"

# Run tests

install:
  - npm ci
script:
  # Run live tests
  - npm run test:run
  # Report live-only coverage to codecov.
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
  # Report live-only coverage to github if running on node 10.
  - if [ "${TRAVIS_NODE_VERSION}" = "10" ]; then npx nyc report --reporter=text | node .github/ci/live-reporter.js; else echo "Not reporting to github..."; fi
  # -------------------------
  # Have nyc run an echo command to clean the output.
  - npx nyc --silent echo ""
  # -------------------------
  # Run mock tests
  - npm run test:run:mock
  # Report mock-only coverage to codecov.
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
  # Report live-only coverage to github if running on node 10.
  - if [ "${TRAVIS_NODE_VERSION}" = "10" ]; then npx nyc report --reporter=text | node .github/ci/mock-reporter.js; else echo "Not reporting to github..."; fi

jobs:
  include:
    - stage: Sauce Labs
      node_js: 10
      script:
        - chmod +x .github/ci/install-sauceconnect.sh
        - npm run test:web:saucelabs
      after_success:
        - node ./.github/ci/saucelabs_bot_travis.js
      env:
        - STAGE=SAUCELABS

# Deploy on tags
deploy:
  provider: npm
  email: $NPME
  api_key: $NPMP
  edge: true # opt in to dpl v2
  on:
    # Only deploy on a tagged commit
    tags: true
    # Don't deploy on the saucelabs stage.
    condition: "$STAGE != SAUCELABS"
    node_js: 10
